import { PropertyType } from "./types";

export const propertiesData:PropertyType[] = [
    {
      id: 1,
      image: require('../../assets/images/HomeContainer/scrollHome1.png'),
      location: 'Pali Hill, Bandra West, Mumbai, MH, India',
      totalValue: '$1,796,192',
      startingAt: '$17,961.92++',
      peopleRegistered: 12,
      details: ['4 Bedrooms', '4 Bath', '2,900 Sqft', '0.13 Acre(s)'],
      featureFrag: 0,
      description: "First Floor Apartment in Jor Bagh",
      descriptionDetails: "This exquisite first-floor apartment is perched on a 515 sqm (617 sq. yds.) plot; the largest plot size of its kind in Jor Bagh, outside the ASI's limitations and in close proximity to Lodhi Gardens. The apartment faces and has access to a park in the front and the rear providing residents with verdant & serene green views. This recently built 275 sqm (-2,960 sq. ft.) apartment has a beautiful living room with...",
      fundRaisingTimeline: 'Ends in 12 Days',
      pricePerShare: '$15,293',
      totalSpots: 72,
      financingOptions: 'Options for both Owners and Shareholders',
      financialModel: 'Indicators for capital appreciation, monthly yield etc.',
      contactPerson: 'Akash Puri',
      contactInfo: 'Seek guidance and an expert opinion from our specialists.'
    },
    {
      id: 2,
      image: require('../../assets/images/HomeContainer/scrollHome2.png'),
      location: 'Vasant Vihar, New Delhi, DL, India',
      totalValue: '$1,679,261',
      startingAt: '$83,963++',
      peopleRegistered: 4,
      details: ['4 Bedrooms', '4 Bath', '2,900 Sqft', '0.13 Acre(s)'],
      featureFrag: 0,
      description: "Luxurious Villa in Vasant Vihar",
      descriptionDetails: "Located in the prestigious Vasant Vihar area, this luxurious villa offers spacious living areas, high-end finishes, and breathtaking views of the surrounding landscape. With 4 bedrooms, 4 bathrooms, and a total area of 2,900 sqft, this villa is ideal for families looking for a peaceful retreat in the heart of New Delhi.",
      fundRaisingTimeline: 'Ends in 10 Days',
      pricePerShare: '$14,938',
      totalSpots: 48,
      financingOptions: 'Options for Owners',
      financialModel: 'Indicators for capital appreciation, monthly yield etc.',
      contactPerson: 'Neha Sharma',
      contactInfo: 'Contact for more details and financing options.'
    },
    {
      id: 3,
      image: require('../../assets/images/HomeContainer/carousal1.png'),
      location: 'Jor Bagh, New Delhi, DL, India',
      totalValue: '$1,679,261',
      startingAt: '$83,963++',
      peopleRegistered: 4,
      details: ['2 Bedrooms', '4 Bath', '2,900 Sqft', '0.13 Acre(s)'],
      featureFrag: 0,
      description: "Cozy Apartment in Jor Bagh",
      descriptionDetails: "This cozy apartment in Jor Bagh offers 2 bedrooms, 4 bathrooms, and a total area of 2,900 sqft. Located in a prime location, this apartment is perfect for individuals or couples looking for a comfortable living space in New Delhi.",
      fundRaisingTimeline: 'Ends in 15 Days',
      pricePerShare: '$7,716',
      totalSpots: 35,
      financingOptions: 'Options for Shareholders',
      financialModel: 'Indicators for capital appreciation, monthly yield etc.',
      contactPerson: 'Rahul Singh',
      contactInfo: 'Schedule a viewing and discuss financing options.'
    },
    {
      id: 4,
      image: require('../../assets/images/HomeContainer/carousal1.png'),
      location: 'Jor Bagh, New Delhi, DL, India',
      totalValue: '$1,679,261',
      startingAt: '$83,963++',
      peopleRegistered: 4,
      details: ['2 Bedrooms', '4 Bath', '2,900 Sqft', '0.13 Acre(s)'],
      featureFrag: 1,
      description: "Stunning Villa in Jor Bagh",
      descriptionDetails: "This stunning villa in Jor Bagh features 2 bedrooms, 4 bathrooms, and a total area of 2,900 sqft. Situated in a sought-after location, this villa offers luxurious amenities and breathtaking views, making it an ideal choice for discerning buyers.",
      fundRaisingTimeline: 'Ends in 8 Days',
      pricePerShare: '$11,728',
      totalSpots: 28,
      financingOptions: 'Options for Shareholders',
      financialModel: 'Indicators for capital appreciation, monthly yield etc.',
      contactPerson: 'Sanjay Kapoor',
      contactInfo: 'Contact for viewing and financing details.'
    },
    {
      id: 5,
      image: require('../../assets/images/HomeContainer/scrollHome2.png'),
      location: 'Vasant Vihar, New Delhi, DL, India',
      totalValue: '$1,679,261',
      startingAt: '$83,963++',
      peopleRegistered: 4,
      details: ['4 Bedrooms', '4 Bath', '2,900 Sqft', '0.13 Acre(s)'],
      featureFrag: 2,
      description: "Modern Apartment in Vasant Vihar",
      descriptionDetails: "This modern apartment in Vasant Vihar offers 4 bedrooms, 4 bathrooms, and a total area of 2,900 sqft. With contemporary design and premium amenities, this apartment provides a comfortable and luxurious living experience in New Delhi.",
      fundRaisingTimeline: 'Ends in 5 Days',
      pricePerShare: '$14,382',
      totalSpots: 60,
      financingOptions: 'Options for Owners',
      financialModel: 'Indicators for capital appreciation, monthly yield etc.',
      contactPerson: 'Rajesh Khanna',
      contactInfo: 'Contact for more information and financing options.'
    },
  ];
  